services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - esnet
    healthcheck:
      test: ["CMD", "curl", "-sS", "http://localhost:9200/_cluster/health?local=true"]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    ports:
      - "5001:5000"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - /var/log:/var/log:ro
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - ./synthetic_logs.log:/usr/share/logstash/synthetic_logs.log
    environment:
      - xpack.monitoring.enabled=false
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - esnet

volumes:
  es_data:
  kibana_data:

networks:
  esnet:
    driver: bridge